apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: #Specification for the deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: #Specification for the pod
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 8080
