kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-name
spec:
  storageCLassName: manual
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resource:
    requests:
     storage: 10Gi